### ISSUE TITLE
Fix API URL bug in CLI

### ISSUE THREAD

**Issue by ssteinerx** [gcushen/mezzanine-api#4]
I'm using Docker, so I'm not using the dev server.

Don't see any documentation on how to change the URL which is queried.

I'll go read the code, but it should be pretty obvious how to use e.g. your Docker machine's address instead of 127.0.0.1:8000.

**Comment by ssteinerx** [comment]
I'm using, specifically, the "mezzanine-client-examples" (posts_list.py et al.), and they always go to 127.0.0.1:8000, even after:
```
mezzanine-cli config api_url http://192.168.99.100/api
```
If there's an optional parameter to either the Mezzanine() api constructor or the resultant object's .get_posts() call, then they should be used to show how to override the URL.

**Comment by gcushen** [comment]
@ssteinerx , thanks for reporting this issue with the API CLI. The CLI project is actually in a separate Github repo dedicated to just the CLI.

The issue seems to be that line 55 of https://github.com/gcushen/mezzanine-client-python/blob/master/mezzanine_client/api.py was originally designed for the use via the API Python SDK  and appears I may have forgotten to update it to check if the API URL has been set in the `settings` object in the case of CLI access.

Hence if you provide API URL via the SDK it should work fine, but the small fix mentioned above may be needed for the CLI.

**Comment by gcushen** [comment]
For example, `settings.api_url` should be checked in line 55 of https://github.com/gcushen/mezzanine-client-python/blob/master/mezzanine_client/api.py .

Feel free to submit a pull request to the CLI/SDK Repo at https://github.com/gcushen/mezzanine-client-python if you fix it, otherwise I'll try to to fix it when I get a moment.

**Comment by pysecuser** [comment]
Thanks for this API, great work! Is there a way to post featured image and/or set it for any post?

**Comment by gcushen** [comment]
This CLI bug has been fixed in v0.2.2 of Mezzanine Client: https://github.com/gcushen/mezzanine-client-python/releases/tag/0.2.2 .

To update the API client using pip: `pip install -U mezzanine-client`
