### ISSUE TITLE
Reverse for 'api-root' not found

### ISSUE THREAD

**Issue by mketiku** [gcushen/mezzanine-api#5]
[requirements.txt](https://github.com/gcushen/mezzanine-api/files/511738/requirements.txt)
[urls.txt](https://github.com/gcushen/mezzanine-api/files/511737/urls.txt)
[settings.txt](https://github.com/gcushen/mezzanine-api/files/511736/settings.txt)

Hi George,

Kudos on the project its really really awesome, just a quick question. When I use your template for mezzanine-api ala 

> ` mezzanine-project -a mezzanine_api project_name && cd $_

My new application works flawlessly. I am able to interact with the api and all that. However when I follow your instructions on how to insert into an existing project I receive the following error:

``Reverse for 'api-root' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []`

Attached are my virtualenv requirements, settings file and url config. 

Could you point me in the right direction as to how to fix this?

**Comment by gcushen** [comment]
I see that your existing project is using:
- Django (1.8.6)
- Mezzanine (4.2.2)
- mezzanine-api (0.5.0)
- djangorestframework (3.4.7)

In the last few major versions of both Mezzanine and Django, the way in which URL routing and namespaces work have changed. It sounds like this issue could be related to that.

For example, one thing you can try is to change `url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),` to just `url(r'^auth/', include('rest_framework.urls')),` in `mezzanine_api/urls.py`. 

Unfortunately, I am very busy on other projects at the moment. You may wish to take a look at the official Django and Mezzanine documentation regarding the URL changes, or ask on the general Mezzanine support forum if there is still an issue. Please try to let me know once you have fixed it so that I can address any potential compatibility bugs.
